name: Build Mobile Apps

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  android-build:
    name: Android Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: mobile-native/package-lock.json

      - name: Install NPM Dependencies
        working-directory: mobile-native
        run: npm ci

      - name: Grant execute permission for gradlew
        working-directory: mobile-native/android
        run: chmod +x gradlew

      - name: Build Android Release APK
        working-directory: mobile-native/android
        run: ./gradlew assembleRelease --no-daemon

      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: android-app-release
          path: mobile-native/android/app/build/outputs/apk/release/app-release.apk

  ios-build:
    name: iOS Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: mobile-native/package-lock.json

      - name: Install NPM Dependencies
        working-directory: mobile-native
        run: npm ci

      - name: Install CocoaPods
        working-directory: mobile-native/ios
        run: |
          pod install

      - name: Build iOS App (Simulator Release)
        working-directory: mobile-native/ios
        run: |
           xcodebuild -workspace MobileNativeApp.xcworkspace \
            -scheme MobileNativeApp \
            -configuration Release \
            -sdk iphonesimulator \
            -derivedDataPath build

      - name: Zip iOS App
        working-directory: mobile-native/ios/build/Build/Products/Release-iphonesimulator
        run: zip -r MobileNativeApp.zip MobileNativeApp.app

      - name: Upload iOS App
        uses: actions/upload-artifact@v4
        with:
          name: ios-app-release-simulator
          path: mobile-native/ios/build/Build/Products/Release-iphonesimulator/MobileNativeApp.zip
